version: '3.8'
services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: user-app-db
      MARIADB_USER: user-app
      MARIADB_PASSWORD: secret-user-app
    ports:
      - "3306:3306"
    networks:
      - db-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "7999:80"  # Porta para não conflitar com o Quarkus
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge